### ISSUE TITLE
In Header.js SafeAreaView is not working in Android

### ISSUE THREAD

**Issue by vefoto-gates** [vefoto-gates/ubereats-clone-vefotogates#1]
I write the styles and flex but header gone to the upper part of the notch please resolve this issue

**Comment by gauravmandall** [comment]
Pull request generated that will help you
and Issue Resolved and if you want give me a star

**Comment by vefoto-gates** [comment]
Thanks @gauravmandall for Resolving this issue I really Appreciated this
